### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by unwenliu** [haozi3156666/canal-python#1]
完整日志：
```
connected to 127.0.0.1:11111
Traceback (most recent call last):
  File "canal_client.py", line 10, in <module>
    client.check_valid(username=b'canal', password=b'canal')
  File "/usr/local/lib/python3.6/site-packages/canal/client.py", line 37, in check_valid
    data = self.connector.read_next_packet()
  File "/usr/local/lib/python3.6/site-packages/canal/connector.py", line 41, in read_next_packet
    data = self.read(self.packet_len)
  File "/usr/local/lib/python3.6/site-packages/canal/connector.py", line 29, in read
    raise Exception('TSocket: Could not read bytes from server')
Exception: TSocket: Could not read bytes from server
```

**Comment by junnl** [comment]
@unwenliu  问题解决了吗，我也遇到一样的问题

**Comment by laizhebujum** [comment]
client.py中
client.subscribe(client_id=b'1234', destination=b'canal_8888', filter=b'.*\\..*') 
检查上述配置中所传destination是否存在，如果不存在，会报上边错误。

client.py在定义def subscribe时候，也定义了默认的client_id和destination，检查下是否和传的一致，如果这块定义为空 即def subscribe(self, client_id, destination, filter): 在调用的时候传递会更好吧
