### ISSUE TITLE
client.get()报错

### ISSUE THREAD

**Issue by sunmingyang1994** [haozi3156666/canal-python#2]
Traceback (most recent call last):
  File "/Users/admin/Desktop/project/dataCollection/canal.py", line 13, in <module>
    message = client.get()
  File "/Users/admin/Desktop/project/dataCollection/canal/client.py", line 85, in get
    message = self.get_without_ack(size)
  File "/Users/admin/Desktop/project/dataCollection/canal/client.py", line 119, in get_without_ack
    ack = CanalProtocol_pb2.PacketType.Ack()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/protobuf/internal/enum_type_wrapper.py", line 95, in __getattr__
    raise AttributeError
AttributeError

**Comment by xingfeT** [comment]
解决了吗， 我也有同样的问题

**Comment by jackylvm** [comment]
CanalProtocol_pb2.PacketType没有Ack函数

CanalProtocol_pb2才有

CanalProtocol_pb2.Ack()

**Comment by yongzheJIN** [comment]
> CanalProtocol_pb2.PacketType没有Ack函数
> 
> CanalProtocol_pb2才有
> 
> CanalProtocol_pb2.Ack()

 这个要改源码吗
